### ISSUE TITLE
why have you forsaken us?!? /s

### ISSUE THREAD

**Issue by StarrHD** [cmdrdahkron/elite-binds#5]
any plans on making a update to the current control scheme for either the xbox or DS4 controllers or is this project dead in the water? would love to use these again since binding is very hard for me to get right i use keyboard and mouse now but im missing the ds4 controls a lot.

**Comment by cmdrdahkron** [comment]
LOL I am _so_ sorry - since I don't use a controller any more I never seem to be able to get around to updating these binds.  Fear not however, as a valiant hero (a new contributor) has emerged to save the day!

**Comment by StarrHD** [comment]
awesome cant wait!

**Comment by laurent-indermuehle** [comment]
It's going to be long... I have converted all the new controls and was ready to push here, but when I tested ingame, the game randomly deactivate bindings. Very hard to test and understand what is going on :( Per example, tonight the game decided that I won't be able to set a key for "Throttle down". I overshoot my station 2 times before discovering that bug.

I also found that the game renamed the key names ("Pad_A" ► GamePad_FaceDown). And that there is alot of errors in the templates (control scheme) from Frontier (duplicates, wrongs values, ...).

**Comment by cliffrowley** [comment]
@Honiix could you upload a before and after? Maybe we can diff them and work out what the game is changing.

Edit: should probably explain what I'm thinking.. I'm wondering specifically if the game is altering the config file when it "forgets" a binding, or whether it's simply ignoring it.

**Comment by laurent-indermuehle** [comment]
I'm already working with a diff tool. And even with it, I'm unable to understand what's going on...

Maybe the game doesn't like my Elite controller. When I limit the travel of the 2 triggers by half and I activate or deactivate that (I need the full range for throttle in the ground vehicule), it's where the problems begins. I'll test more with my standard xbox controller.

I can make a "dev" branch and push my work in progress :)

**Comment by cliffrowley** [comment]
Interesting. I also have an Elite controller but I've never used it for, er, Elite. If you need me to test something over here I probably can.

**Comment by laurent-indermuehle** [comment]
@cliffrowley together,  we are stronger ;) Thanks you for your offer. I'm glad I'm not alone to test. I've edited the 1308 lines one by one... a mistake is easy to make even with my diff-tool.

I've pushed a new "Dahkron-Xbox.binds" file in branch "fix-ver-3". Please have a look at the bottom of the readme to see what I've changed. The pictures are not updated yet.

**Comment by laurent-indermuehle** [comment]
I may have fixed the problem. I made a small typo (GAmePad instead of GamePad) that is fixed in the last commit in branch "fix-ver-3". I tried to reload the game two times and every binds seem to work now. Do you confirm @cliffrowley?

**Comment by cliffrowley** [comment]
I won't be able to confirm this evening as I'm tied up this evening, but don't wait for me to merge things into master - I won't be looking over your shoulder ;-)

**Comment by laurent-indermuehle** [comment]
Ok, I've merge into master: 9b4da6fab3d22343674d40c78000e7b407a6c408
I close this issue :)
